service: media-converter

provider:
  name: google
  runtime: nodejs14
  project: 	helical-parity-344010
  credentials: ~/.config/gcloud/application_default_credentials.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  helloWorld:
    handler: http
    events:
      - http: /