service: my-gcf-service

provider:
  name: google
  runtime: nodejs
  project: my-serverless-project-1234
  credentials: ~/.config/gcloud/application_default_credentials.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path